src/AppBundle/Entity/Prediction.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Prediction
 *
 * @ORM\Table(name="prediction")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PredictionRepository")
 */
class Prediction
{
    
    const POINTS_CORRECT = 10;
    const POINTS_BONUS = 10;
    
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var \DateTime $created
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var \DateTime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;
    
    /**
     * 
     * @ORM\ManyToOne(targetEntity="Courtcase", inversedBy="Predictions")
     * @ORM\JoinColumn(name="courtcase_id", referencedColumnName="id")
     */
    private $courtcase;
    
    /**
     * 
     * @ORM\ManyToOne(targetEntity="User", inversedBy="Predictions")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;
    
    /**
     * 
     * @ORM\OneToMany(targetEntity="PredictionJudge", mappedBy="prediction", cascade={"persist"})
     */
    private $predictionJudges;
    
    /**
     * 
     * @ORM\OneToMany(targetEntity="Notification", mappedBy="prediction", cascade={"persist"})
     */
    private $notifications;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="is_ruling", type="boolean", nullable=true)
     */
    private $isRuling;
    
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function __toString()
    {
        
        return $this->calcPrediction();
        
    }
    
    public function getRequiredPredictions()
    {
        
        $count = 0;
        
        foreach ($this->getPredictionJudges() as $predictionJudge) {
            
            if (!$predictionJudge->getJudge()->isRecused($this->getCourtcase()->getId())) {
                
                $count += 1;
                
            }
            
        }
        
        return $count;
        
    }
    
    /**
     * Set courtcase
     *
     * @param \AppBundle\Entity\Courtcase $courtcase
     *
     * @return Prediction
     */
    public function setCourtcase(\AppBundle\Entity\Courtcase $courtcase = null)
    {
        $this->courtcase = $courtcase;

        return $this;
    }

    /**
     * Get courtcase
     *
     * @return \AppBundle\Entity\Courtcase
     */
    public function getCourtcase()
    {
        return $this->courtcase;
    }

    /**
     * Set user
     *
     * @param \AppBundle\Entity\User $user
     *
     * @return Prediction
     */
    public function setUser(\AppBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->predictionJudges = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add predictionJudge
     *
     * @param \AppBundle\Entity\PredictionJudge $predictionJudge
     *
     * @return Prediction
     */
    public function addPredictionJudge(\AppBundle\Entity\PredictionJudge $predictionJudge)
    {
        $this->predictionJudges[] = $predictionJudge;

        return $this;
    }

    /**
     * Remove predictionJudge
     *
     * @param \AppBundle\Entity\PredictionJudge $predictionJudge
     */
    public function removePredictionJudge(\AppBundle\Entity\PredictionJudge $predictionJudge)
    {
        $this->predictionJudges->removeElement($predictionJudge);
    }

    /**
     * Get predictionJudges
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPredictionJudges()
    {
        return $this->predictionJudges;
    }
    
    
    public function getPredictionJudgesOrdered()
    {
        
        $ordered = array();
        
        // add the chief justices.
        foreach ($this->predictionJudges as $predictionJudge) {
            
            if ($predictionJudge->getJudge()->getJusticeTitle()->getPriority() == 1) {
                
                $ordered[] = $predictionJudge;
                
            }
            
        }
        
        // add the chief justices.
        foreach ($this->predictionJudges as $predictionJudge) {
            
            if ($predictionJudge->getJudge()->getJusticeTitle()->getPriority() == 2) {
                
                $ordered[] = $predictionJudge;
                
            }
            
        }
        
        // add the chief justices.
        foreach ($this->predictionJudges as $predictionJudge) {
            
            if ($predictionJudge->getJudge()->getJusticeTitle()->getPriority() == 3) {
                
                $ordered[] = $predictionJudge;
                
            }
            
        }
        
        return $ordered;
        
    }
    
    public function getPredictionForJudge($id)
    {
        
        foreach ($this->getPredictionJudges() as $predictionJudge) {
            
            if ($predictionJudge->getJudge()->getId() === $id) {
                
                return $predictionJudge;
                
            }
            
        }
        
        return null;
        
    }
    
    public function calcPrediction($resultType="txt")
    {
        
        $upheld = $notupheld = 0;
        
        $result = "";
        
        foreach ($this->getPredictionJudges() as $predictionJudge) {
            
            if (!$predictionJudge->getJudge()->isRecused($this->getCourtcase()->getId())) {
                
                if ($predictionJudge->getAppealUpheld()) {

                    $upheld = $upheld + 1;

                } else {

                    $notupheld = $notupheld + 1;

                }
                
            }
        }
        
        if ($resultType == "txt") {
            
            if ($upheld > $notupheld) {

                $result = $upheld ." - ".$notupheld . " Appeal will be upheld";

            } else if ($upheld < $notupheld) {

                $result = $upheld ." - ".$notupheld . " Appeal will be dismissed";

            } else {

                $result = $upheld ." - ".$notupheld . " Lower court decision";

            }

            if ($this->getIsRuling()) {

                $result = str_replace("will be ", "", $result);

            }
            
        } else if ($resultType == "txtSimple") {
            
            if ($upheld > $notupheld) {

                return "upheld";

            } else if ($upheld < $notupheld) {

                return "dismissed";

            } else {

                return null;

            }
            
        }
        
        return $result;
        
    }
    
    
    public function generateResults()
    {
        
        $caseResults = [
            "casesPredictedCorrect" => 0, 
            "totalEntries" => 1, 
            "totalCases" => 0, 
            "individualJudges" => 0, 
            "totalJudges" => 0, 
            "score" => 0, 
            "maxScore" => 0, 
            "uberMaxScore" => 0,
            "leagueScore" => 0,
            ];
        
        if ($this->isPredictionCorrect()) {
            
            $caseResults["casesPredictedCorrect"] = 1;
            
        }
        
        $results = $this->countCorrectJudges();
        
        $caseResults["individualJudges"] = $results["correct"];
        
        $caseResults["score"] = $results["score"];
        
        $caseResults["maxScore"] = $this->getMaxScore();        
        
        $caseResults["totalJudges"] = count($this->getPredictionJudges());
               
        $caseResults["leagueScore"] = $this->getScore();
        
        return $caseResults;
        
    }
    
    public function getMaxScore()
    {
        
        return count($this->getPredictionJudges()) * self::POINTS_CORRECT + self::POINTS_BONUS;
        
    }
    
    public function isPredictionCorrect($ruling = null)
    {
        
        if (null === $ruling) {
            
            if ($this->getCourtcase()->getRuling()) {

                if ($this->calcPrediction("txtSimple") === $this->getCourtcase()->getRuling()->calcPrediction("txtSimple")) {

                    return true;

                }
            }
        }
        
        if (null !== $ruling) {
               
            if ($this->calcPrediction("txtSimple") === $ruling->calcPrediction("txtSimple")) {

                return true;

            }

        }
        
        return false; 
        
    }
    
    public function countCorrectJudges($ruling = null)
    {
        
        $correct = 0;
        $points = 0;
        
        if (null === $ruling) {
            
            if ($this->getCourtcase()->getRuling()) {

                foreach ($this->getCourtcase()->getRuling()->getPredictionJudges() as $predictionJudge) {

                    if (null !== $this->getPredictionForJudge($predictionJudge->getJudge()->getId()) && ($this->getPredictionForJudge($predictionJudge->getJudge()->getId())->getAppealUpheld() === $predictionJudge->getAppealUpheld())) {

                        $correct = $correct + 1;

                        $points = $points + self::POINTS_CORRECT;

                    }

                }

            }

            if ($this->isPredictionCorrect()) {

                $points = $points + self::POINTS_BONUS;

            }
        
        }
        
        if (null !== $ruling) {
            
            foreach ($ruling->getPredictionJudges() as $predictionJudge) {

src/AppBundle/Controller/CasesController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use AppBundle\Service\Util;

use AppBundle\Entity\Jurisdiction;
use AppBundle\Entity\Prediction;

class CasesController extends Controller
{
    
    /**
     * @Route("/prediction/{slug}", name="lexfutures_prediction_edit")
     * @param string $slug
     * @param Request $request
     */
    public function predictionAction(Request $request, $slug)
    {
        
        $util = $this->get(Util::class);
        
        $em = $this->getDoctrine()->getManager();
        
        $case = $this->getDoctrine()->getRepository('AppBundle:Courtcase')->findOneBySlug($slug);
        
        if (null === $case) {
            
            $this->get('session')->getFlashBag()->add("errormsg", "We could not find that case!");
            
            return $this->redirectToRoute('lexfutures_dashboard');
            
        }
                
        if ($case->getStatusToString() === 'decided' || $case->getRemovedFromRole()) {
            
            $this->get('session')->getFlashBag()->add("errormsg", "You may no longer make a prediction for that case!");
            
            return $this->redirectToRoute('lexfutures_cases', ['slug' => $case->getJurisdiction()->getSlug()]);
            
        }
        
        if ($this->getUser()) {
            
            $prediction = $util->getUserPrediction($this->getUser(), $case);
        
            if (null === $prediction) {

                $prediction = $util->initPrediction($case, $this->getUser());

            } 
            
        } else {
            
            $prediction = $util->initPrediction($case, null);
            
        }
        
        
        $errors = array();
        
        if ($request->getMethod() == 'POST') {
            
            if ($case->getStatusToString() === 'decided' || $case->getRemovedFromRole()) {
            
                $this->get('session')->getFlashBag()->add("errormsg", "You may no longer make a prediction for that case!");

                return $this->redirectToRoute('lexfutures_cases', ['slug' => $case->getJurisdiction()->getSlug()]);

            }
            
            
            if ($util->validatePrediction($prediction, $_POST)) {
                
                $util->updatePrediction($prediction, $_POST);
                
                $em->persist($prediction);

                $em->flush();

                // TODO: add a flashMessage

                return $this->redirectToRoute('lexfutures_cases', ['slug' => $prediction->getCourtcase()->getJurisdiction()->getSlug()]);
                
            } else {
                
                $errors[] = "Please capture a prediection for each of the justices!";
                
            }
        }
        
        return $this->render('AppBundle:cases:prediction.html.twig', [
            'prediction' => $prediction,
            'jurisdiction' => $case->getJurisdiction(),
            'errors' => $errors,
        ]);
        
    }
    
    /**
     * 
     * Show the cases for the particular jurisdiction
     * 
     * @Route("/lex/bio/{slug}", name="lexfutures_jude_bio")
     */
    public function judgesBioAction(Request $request, $slug)
    {
        
        $util = $this->get(Util::class);
        
        $em = $this->getDoctrine()->getManager();
        
        $judge = $this->getDoctrine()->getRepository('AppBundle:Judge')->findOneBySlug($slug);
        
        if (null === $judge) {
            
            $this->get('session')->getFlashBag()->add("errormsg", "We could not find that judge!");
            
            return $this->redirectToRoute('lexfutures_dashboard');
            
        }
        
        return $this->render('AppBundle:cases:judgeBio.html.twig', [
            'judge' => $judge,
            'jurisdiction' => $judge->getJurisdiction(),
        ]);
        
    }
    
    /**
     * 
     * Show the cases for the particular jurisdiction
     * 
     * @Route("/lex/case/details/{slug}", name="lexfutures_case_deatils")
     */
    public function caseDetailsAction(Request $request, $slug)
    {
        
        $util = $this->get(Util::class);
        
        $em = $this->getDoctrine()->getManager();
        
        $case = $this->getDoctrine()->getRepository('AppBundle:Courtcase')->findOneBySlug($slug);
        
        if (null === $case) {
            
            $this->get('session')->getFlashBag()->add("errormsg", "We could not find that case!");
            
            return $this->redirectToRoute('lexfutures_dashboard');
            
        }
        
        return $this->render('AppBundle:cases:details.html.twig', [
            'case' => $case,
            'jurisdiction' => $case->getJurisdiction(),
        ]);
        
    }
    
    /**
     * 
     * Show the cases for the particular jurisdiction
     * 
     * @Route("/league/{slug}", name="lexfutures_cases")
     */
    public function listAction(Request $request, $slug)
    {
                
        $jurisdiction = $this->getDoctrine()->getRepository('AppBundle:Jurisdiction')->findOneBySlug($slug);
        
        if (null === $jurisdiction) {
            
            return $this->redirectToRoute('lexfutures_dashboard');
            
        }
        
        $cases = $this->getJurisditionCases($jurisdiction);
        
        return $this->render('AppBundle:cases:list.html.twig', [
            'cases' => $cases, 'jurisdiction' => $jurisdiction
        ]);
        
    }
    
    /**
     * Return an array of cases for the given jurisdiction. Inject the users
     * prediction for each case and inject the actual result
     * 
     * TODO: add in seasons so that we can reset the ladder and competition
     * 
     * @param Jurisdiction $jurisdiction
     * @return array
     */
    public function getJurisditionCases(Jurisdiction $jurisdiction)
    {
        
        $finalcases = array();
        
        $util = $this->get(Util::class);
        
        //$helper = $this->get('lex.core.util');
        
        $cases = $this->getDoctrine()->getRepository('AppBundle:Courtcase')->findBy(["jurisdiction" => $jurisdiction->getId(), "season" => $jurisdiction->getCurrentSeason()->getId()]);
        
        foreach ($cases as $case) {
            
            if ($this->getUser()) {
                
                $finalcases[] = array("case" => $case, "prediction" => $util->getUserPrediction($this->getUser(), $case));
                
            } else {
                
                $finalcases[] = array("case" => $case, "prediction" => null);
                
            }
            
        }
        //$helper->getUserPrediction($case)
        
        // Order Cases by hearing date
        
        usort($finalcases, array($this, 'caseSort'));
        
        return $finalcases;
        
    }
    
    private static function caseSort($a, $b) {
        
        if ($a["case"]->getScheduledDate() == $b["case"]->getScheduledDate()) {
            
            return 0;
            
        }
        
        return ($a["case"]->getScheduledDate() < $b["case"]->getScheduledDate()) ? -1 : 1;
        
    }

    private static function caseSortRev($a, $b) {
        
        if ($a["case"]->getScheduledDate() == $b["case"]->getScheduledDate()) {
            
            return 0;
            
        }
        
        return ($a["case"]->getScheduledDate() > $b["case"]->getScheduledDate()) ? -1 : 1;
        
    }
}

src/AppBundle/Resources/views/cases/prediction.html.twig
{% extends 'AppBundle::frontbase.html.twig' %}
{% block maincontent %}
<link rel="stylesheet" href="/font-awesome-4.7.0/font-awesome-4.7.0/css/font-awesome.min.css">
<script src="/js/jquery.1.10.2.min.js"></script>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" id="loginNotification">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Please Login</h4>
      </div>
      <div class="modal-body">
          <p>You must be logged in to submit a prediction. Click here to <a style="color: blue;" href="{{path('fos_user_security_login')}}">login</a> or <a style="color: blue;" href="{{path('fantasy_league')}}">register</a> if you have not logged in before</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="dismissModal" data-dismiss="modal">OK</button>
        
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="row">
        {# <div class="col-xs-12 pall10 f-black text-center f-black">
            <p>
                The LexFutures Court Prediction League is presented in <br/>partnership with UCT Law @ Work &amp; Juta Law.

            </p>
        </div>
        <div class="col-xs-12 col-sm-6 tmargin20 f-black text-center">

            <img src="/images/Juta-logo-small.png" class="img-responsive sponsor-logo">
            
            <p class="tmargin20"><a href="https://twitter.com/JutaLaw" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i> @JutaLaw</a></p>
        </div>

        <div class="col-xs-12 col-sm-6 tmargin20 f-black text-center ">

            <img src="/images/uctlogo.png" class="img-responsive sponsor-logo">
            
            <p class="tmargin20"><a href="https://twitter.com/UCT_Law_at_work" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i>@UCTLaw@Work</a></p>
            
        </div> #}
        <div class="row">
            <div class="col-xs-12 text-center f-black">
                <h2 style="margin-bottom: 6px !important;">{{jurisdiction.anname}} {{jurisdiction.court}}</h2>
                {#<a href="{{path('lexfutures_leaderboard', {'id': jurisdiction.id})}}"><small>leader board</small></a>#}
                <h3 style="margin-top: 12px !important;">{{prediction.courtcase.name}}</h3>
                {% for note in prediction.courtcase.notes %}
                <p>{{note.note}}</p>    
                {% endfor %}
            </div>
        </div>
    </div>
    
    {#
    <div class="row">
        <div class="col-xs-12 col-md-9 text-center tmargin20">
            <img src="/images/Juta-logo-small.png" class="img-responsive" style="margin: 0 auto; width: 130px;">
            <h2 style="margin-bottom: 6px !important;">{{jurisdiction.anname}} Court</h2>
            <a href="{{path('lexfutures_leaderboard', {'id': jurisdiction.id})}}"><small>leader board</small></a>
        </div>
        <div class="col-xs-12 col-md-3 text-center">
            <img src="/images/400px-uct_alt_ntp.png" class="img-responsive">
            The LexFutures Court Prediction League is presented in partnership with UCT Law @ Work.
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <h4>{{prediction.courtcase.name}}</h4>
        </div>
    </div>
    #}
    <div class="row">
        <div class="col-lg-12">
        {% for flashMessage in errors %}
            <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-times scred"></i> ERROR!</strong> {{ flashMessage }}</div>
        {% endfor %}    
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">    
            <form method="POST" id="predictionForm" name="predictionForm">
            <table class="table table-striped table-condensed"> 
                <thead>
                    <tr style="border-color: red !important;">
                        <th style="border-right-color: #fff !important; border-left-color: #fff !important;"></th>                        
                        <th colspan="3" style="border-right-color: #fff !important;">Click to enter your prediction below</th>
                    </tr>
                    <tr>                        
                        <th>Judges</th>
                        <th>Uphold</th>
                        <th>Dismiss</th>
                        <th>Judges Biography</th>
                    </tr>
                </thead>
                <tbody>
                {% for predictionJudge in prediction.predictionJudgesOrdered %}
                {% if predictionJudge.judge.isRecused(prediction.courtcase.id) %}{% else %}
                <input class="justicePrediction" type="hidden" name="justice_{{predictionJudge.judge.id}}" id="justice_{{predictionJudge.judge.id}}" value="{% if predictionJudge.appealUpheld is defined and predictionJudge.appealUpheld is not null %}{% if predictionJudge.appealUpheld %}1{% else %}0{% endif %}{% endif %}">    
                {% endif %}
                {% if predictionJudge.judge.isRecused(prediction.courtcase.id) %}
                <tr class="recused">
                    <td>
                        {{predictionJudge.judge.justiceTitle.name}} {{predictionJudge.judge.name}} (<span style="color: red;"><i><strong>recused</strong></i></span>)
                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>
                        {% if judge.profileLine1 is defined and judge.profileLine1 is not null and judge.profileLine1 != '' %}
                        <a class="visible" href="{{judge.profileLine1|raw}}" target="_blank">View Biography</a>
                        {% endif %}
                    </td>
                </tr>    
                {% else %}
                <tr>
                    <td>
                        {{predictionJudge.judge.justiceTitle.name}} {{predictionJudge.judge.name}}
                    </td>
                    <td class="clickable upheld" id="upheld_{{predictionJudge.judge.id}}">
                        {% if predictionJudge.appealUpheld is defined and predictionJudge.appealUpheld is not null %}
                        {% if predictionJudge.appealUpheld %}
                        <i class="fa fa-check green-i" aria-hidden="true"></i>
                        {% endif %}
                        {% endif %}
                    </td>
                    <td class="clickable notupheld" id="notupheld_{{predictionJudge.judge.id}}">
                        {% if predictionJudge.appealUpheld is defined and predictionJudge.appealUpheld is not null %}
                        {% if not predictionJudge.appealUpheld %}
                        <i class="fa fa-times red-i" aria-hidden="true"></i>
                        {% endif %}
                        {% endif %}
                    </td>
                    <td>
                        {% if predictionJudge.judge.profileLine1 is defined and predictionJudge.judge.profileLine1 is not null and predictionJudge.judge.profileLine1 != '' %}
                        <a class="visible" href="{{predictionJudge.judge.profileLine1|raw}}" target="_blank">View Biography</a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
            {% if app.user %}
            <input type="submit" value="save Prediction" class="btn btn-lrg btn-primary">
            {% else %}
            <input type="button" value="save Prediction" class="btn btn-lrg btn-primary" id="submitPredictionNoAuth">    
            {% endif %}
            </form>
            <p style="color: #000;" class="tmargin10">
                You can edit your prediction at any time before the judgment is handed down.
            </p>
        </div>
        <div class="col-xs-12">
            <br/>
        </div>
    </div>
</div>
<script>

$(document).ready(function() {
    
    {% if app.user is defined and app.user is not null %}
        
    {% else %}
        $('#loginNotification').modal();
    {% endif %}
    
    
    $("body").on("click", "#submitPredictionNoAuth", function (e) {
        $('#loginNotification').modal();
    });
    
    $("body").on("click", ".upheld.clickable", function (e) {
        
        var ident = $(this).attr("id");
        var id = partify(ident, "_", 1);
        
        $("#justice_"+id).val('1');
        
        $("#upheld_"+id).html('<i class="fa fa-check green-i" aria-hidden="true"></i>');
        $("#notupheld_"+id).html('');
    });
    
    $("body").on("click", ".notupheld.clickable", function (e) {
        
        var ident = $(this).attr("id");
        var id = partify(ident, "_", 1);
        
        $("#justice_"+id).val('0');
        
        $("#upheld_"+id).html('');
        $("#notupheld_"+id).html('<i class="fa fa-times red-i" aria-hidden="true"></i>');
    });
    
    
});

function checkinput()
{
    
    var checks = 0;
    var totals = 0;
    
    $("#predictionForm input[type=hidden]").each(function() {
        
        if (this.value === "0" || this.value === "1" || this.value === 0 || this.value === 1) {
            
            checks = checks + 1;
            
        }
        
        totals = totals + 1;
        
    });
    
    //console.log(checks+"|"+totals);
    
    if (checks > 0 && checks < totals) {
        
        
        
        return true;
        
    }
    
    return false;
    
}

window.onbeforeunload = function() {
    
    if (checkinput()) {
    
        return "You haven't saved your prediction, are you sure you want to leave the page?";
    
    }
};

function partify(string, seperator, index)
{
    
    var parts = string.split(seperator);
    
    return parts[index];
    
}
</script>
{% endblock maincontent %}

{#
<link rel="stylesheet" href="/font-awesome-4.7.0/font-awesome-4.7.0/css/font-awesome.min.css">
<style media="screen" type="text/css">
.clickable {cursor: pointer;}

</style>
<script src="/js/jquery.1.10.2.min.js"></script>
<h1>{{prediction.courtcase.jurisdiction.anname}} Court</h1>

<!-- Upcoming Cases -->
<h4>{{prediction.courtcase.name}}</h4>
<form method="POST" id="predictionForm" name="predictionForm">
<table width="100%" cellpadding="10" cellspacing="10" border="1">    
{% for predictionJudge in prediction.predictionJudges %}
<input type="hidden" name="justice_{{predictionJudge.judge.id}}" id="justice_{{predictionJudge.judge.id}}" value="{% if predictionJudge.appealUpheld is defined and predictionJudge.appealUpheld is not null %}{% if predictionJudge.appealUpheld %}1{% else %}0{% endif %}{% endif %}">
<tr>
    <td>
        {{predictionJudge.judge.justiceTitle.name}} {{predictionJudge.judge.name}}
    </td>
    <td class="clickable upheld" id="upheld_{{predictionJudge.judge.id}}">
        {% if predictionJudge.appealUpheld is defined and predictionJudge.appealUpheld is not null %}
        {% if predictionJudge.appealUpheld %}
        <i class="fa fa-check" aria-hidden="true"></i>
        {% endif %}
        {% endif %}
    </td>
    <td class="clickable notupheld" id="notupheld_{{predictionJudge.judge.id}}">
        {% if predictionJudge.appealUpheld is defined and predictionJudge.appealUpheld is not null %}
        {% if not predictionJudge.appealUpheld %}
        <i class="fa fa-times" aria-hidden="true"></i>
        {% endif %}
        {% endif %}
    </td>
    <td>
        Judge Bio
    </td>
    <td>
        Crowd Prediction
    </td>
</tr>
{% endfor %}
</table>
<input type="submit" value="Predict">
</form>
<script>
$(document).ready(function() {
    
    $("body").on("click", ".upheld.clickable", function (e) {
        
        var ident = $(this).attr("id");
        var id = partify(ident, "_", 1);
        
        $("#justice_"+id).val('1');
        
        $("#upheld_"+id).html('<i class="fa fa-check" aria-hidden="true"></i>');
        $("#notupheld_"+id).html('');
    });
    
    $("body").on("click", ".notupheld.clickable", function (e) {
        
        var ident = $(this).attr("id");
        var id = partify(ident, "_", 1);
        
        $("#justice_"+id).val('0');
        
        $("#upheld_"+id).html('');
        $("#notupheld_"+id).html('<i class="fa fa-times" aria-hidden="true"></i>');
    });
});

function partify(string, seperator, index)
{
    
    var parts = string.split(seperator);
    
    return parts[index];
    
}
</script>
#}