src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;

use FOS\UserBundle\Model\User as BaseUser;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\Common\Collections\ArrayCollection;


/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @var \DateTime $created
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var \DateTime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;
    
    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=255, nullable=true)
     * 
     * @Assert\NotBlank(
     *      message = "First Name is required"
     * )
     */
    private $firstName;
    
    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=255, nullable=true)
     * 
     * @Assert\NotBlank(
     *      message = "Last Name is required"
     * )
     */
    private $lastName;
    
    /**
     * 
     * @ORM\ManyToOne(targetEntity="EducationLevel")
     * @ORM\JoinColumn(name="education_level_id", referencedColumnName="id")
     * 
     */
    private $educationLevel;
    
    /**
     * 
     * @ORM\ManyToOne(targetEntity="Occupation")
     * @ORM\JoinColumn(name="occupation_id", referencedColumnName="id")
     * 
     */
    private $occupation;
    
    /**
     * 
     * @ORM\OneToMany(targetEntity="Prediction", mappedBy="user")
     */
    private $predictions;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="accept_terms", type="boolean", nullable=false)
     */
    private $acceptTerms;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="research_terms", type="boolean", nullable=true)
     */
    private $researchTerms;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="marketing_terms", type="boolean", nullable=true)
     */
    private $marketingTerms;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="isFixture", type="boolean", nullable=true)
     */
    private $isFixture;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="unsub", type="boolean", nullable=true)
     */
    private $unsub;
    
    /**
     * @var string
     *
     * @ORM\Column(name="country", type="string", length=255, nullable=true)
     * 
     */
    private $country;
    
    /**
     * One User has Many Notes.
     * @ORM\OneToMany(targetEntity="Note", mappedBy="creator")
     */
    private $notes;
    
    /**
     * @var \DateTime $loginOffsetTimer

     * @ORM\Column(type="datetime", nullable=true)
     */
    private $loginOffsetTimer;
    
    public function __construct()
    {
        
        parent::__construct();
        
        $this->addRole("ROLE_FRONT_USER");
        
        $this->setAcceptTerms(false);
        
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function getCategory()
    {
        
        if (null !== $this->getOccupation()) {
        
            if ($this->getOccupation()->getId() === 4 || $this->getOccupation()->getId() === 5 || $this->getOccupation()->getId() === 7) {

                return "Student";

            } else if ($this->getOccupation()->getId() === 9) {

                return "Other";

            } else {

                return "Law Professionals";

            }
            
        } else {
            
            return "Other";
            
        }
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return User
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return User
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     *
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }
    
    /**
     * Overriding the parent setEmail to set the users username to their email
     * @param type $email
     */
    public function setEmail($email){
        
        parent::setEmail($email);
        
        $this->username = $email;
        
    }

    /**
     * Set educationLevel
     *
     * @param \AppBundle\Entity\EducationLevel $educationLevel
     *
     * @return User
     */
    public function setEducationLevel(\AppBundle\Entity\EducationLevel $educationLevel = null)
    {
        $this->educationLevel = $educationLevel;

        return $this;
    }

    /**
     * Get educationLevel
     *
     * @return \AppBundle\Entity\EducationLevel
     */
    public function getEducationLevel()
    {
        return $this->educationLevel;
    }

    /**
     * Set occupation
     *
     * @param \AppBundle\Entity\Occupation $occupation
     *
     * @return User
     */
    public function setOccupation(\AppBundle\Entity\Occupation $occupation = null)
    {
        $this->occupation = $occupation;

        return $this;
    }

    /**
     * Get occupation
     *
     * @return \AppBundle\Entity\Occupation
     */
    public function getOccupation()
    {
        return $this->occupation;
    }

    /**
     * Set acceptTerms
     *
     * @param boolean $acceptTerms
     *
     * @return User
     */
    public function setAcceptTerms($acceptTerms)
    {
        $this->acceptTerms = $acceptTerms;

        return $this;
    }

    /**
     * Get acceptTerms
     *
     * @return boolean
     */
    public function getAcceptTerms()
    {
        return $this->acceptTerms;
    }

    /**
     * Set researchTerms
     *
     * @param boolean $researchTerms
     *
     * @return User
     */
    public function setResearchTerms($researchTerms)
    {
        $this->researchTerms = $researchTerms;

        return $this;
    }

    /**
     * Get researchTerms
     *
     * @return boolean
     */
    public function getResearchTerms()
    {
        return $this->researchTerms;
    }

    /**
     * Set marketingTerms
     *
     * @param boolean $marketingTerms
     *
     * @return User
     */
    public function setMarketingTerms($marketingTerms)
    {
        $this->marketingTerms = $marketingTerms;

        return $this;
    }

    /**
     * Get marketingTerms
     *
     * @return boolean
     */
    public function getMarketingTerms()
    {
        return $this->marketingTerms;
    }

    /**
     * Add prediction
     *
     * @param \AppBundle\Entity\Prediction $prediction
     *
     * @return User
     */
    public function addPrediction(\AppBundle\Entity\Prediction $prediction)
    {
        $this->predictions[] = $prediction;

        return $this;
    }

    /**
     * Remove prediction
     *
     * @param \AppBundle\Entity\Prediction $prediction
     */
    public function removePrediction(\AppBundle\Entity\Prediction $prediction)
    {
        $this->predictions->removeElement($prediction);
    }

    /**
     * Get predictions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPredictions()
    {
        return $this->predictions;
    }
    
    public function getFullname()
    {
        
        return trim($this->firstName." ".$this->lastName);
        
    }
    
    public function printname($length = 16)
    {
        
        if (strlen($this->getFullname()) <= $length) {
            
            return $this->getFullname();
            
        } else {
            
            return substr($this->getFullname(), 0, $length-3)."...";
            
        }
        
    }

    /**
     * Add note
     *
     * @param \AppBundle\Entity\Note $note
     *
     * @return User
     */
    public function addNote(\AppBundle\Entity\Note $note)
    {
        $this->notes[] = $note;

        return $this;
    }

    /**
     * Remove note
     *
     * @param \AppBundle\Entity\Note $note
     */
    public function removeNote(\AppBundle\Entity\Note $note)
    {
        $this->notes->removeElement($note);
    }

    /**
     * Get notes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Set isFixture
     *
     * @param boolean $isFixture
     *
     * @return User
     */
    public function setIsFixture($isFixture)
    {
        $this->isFixture = $isFixture;

        return $this;
    }

    /**
     * Get isFixture
     *
     * @return boolean
     */
    public function getIsFixture()
    {
        return $this->isFixture;
    }

    /**
     * Set country
     *
     * @param string $country
     *
     * @return User
     */
    public function setCountry($country)
    {

src/AppBundle/Resources/views/admin/jurisdictionCaseAdd.html.twig
{% extends 'AppBundle::adminbase.html.twig' %}
{% block title %}Dashboard - Student Hub Admin{% endblock %}

{% block stylesheets %}          
    {{ parent() }}
    <!-- DataTables CSS -->
    <link href="/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/bootstrap-datetimepicker-master/build/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block pagecontent %}    
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{jurisdiction.name}} <a href="{{app.request.headers.get('referer')}}"><img src="/images/back-btn.jpg" style="height: 40px;"></a>{#<a class="btn btn-danger btn-xs" href="{{app.request.headers.get('referer')}}">back</a></h1>#}
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                {% for flashMessage in app.session.flashbag.get('successmsg') %}
                    <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scgreen"></i> Success!</strong> {{ flashMessage }}</div>
                {% endfor %}
                {% for flashMessage in app.session.flashbag.get('errormsg') %}
                    <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scred"></i> Error!</strong> {{ flashMessage }}</div>
                {% endfor %}                
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Add a Court Case to {{jurisdiction.name}}                            
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <form action="" method="post" id="stdform" name="updateform">
                                <div class="col-xs-8 col-md-4">
                                    <div class="form-group">
                                        {{ form_row(form.name, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control'} })}}
                                    </div>
                                    <div class="form-group">
                                        {{ form_row(form.scheduledDate, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control datetimepicker'} })}}
                                    </div>
                                    <div class="form-group">
                                        {{ form_row(form.isLeague, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control'} })}}
                                    </div>
                                    
                                    <div class="form-group">
                                        <input type="submit" value="Add Court Case" class="smbt-button btn btn-primary">
                                    </div>
                                    {{ form_rest(form) }}
                                </div> 
                                </form>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
{% endblock pagecontent %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/bootstrap-datetimepicker-master/build/js/bootstrap-datetimepicker.min.js"></script>    
    <script>
    $(document).ready(function() {

        $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD hh:mm'
        });

    });
    </script>
{% endblock javascripts %}    

src/AppBundle/Resources/views/admin/jurisdictionCaseEdit.html.twig
{% extends 'AppBundle::adminbase.html.twig' %}
{% block title %}Dashboard - Student Hub Admin{% endblock %}

{% block stylesheets %}          
    {{ parent() }}
    <!-- DataTables CSS -->
    <link href="/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/bootstrap-datetimepicker-master/build/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block pagecontent %}    
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{jurisdiction.name}} <a href="{{path('lexfutures_admin_jurisdiction_cases', {'id': jurisdiction.id})}}"><img src="/images/back-btn.jpg" style="height: 40px;"></a></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                {% for flashMessage in app.session.flashbag.get('successmsg') %}
                    <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scgreen"></i> Success!</strong> {{ flashMessage }}</div>
                {% endfor %}
                {% for flashMessage in app.session.flashbag.get('errormsg') %}
                    <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scred"></i> Error!</strong> {{ flashMessage }}</div>
                {% endfor %}                
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Add a Court Case to {{jurisdiction.name}}                            
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <form action="" method="post" id="stdform" name="updateform">
                                <div class="col-xs-8 col-md-4">
                                    <div class="form-group">
                                        {{ form_row(form.name, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control'} })}}
                                    </div>
                                    <div class="form-group">
                                        {{ form_row(form.scheduledDate, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control datetimepicker'} })}}
                                    </div>
                                    <div class="form-group">
                                        {{ form_row(form.isLeague, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control'} })}}
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" value="Update Court Case" class="smbt-button btn btn-primary">
                                    </div>
                                    {{ form_rest(form) }}
                                </div> 
                                </form>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
{% endblock pagecontent %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/bootstrap-datetimepicker-master/build/js/bootstrap-datetimepicker.min.js"></script>    
    <script>
    $(document).ready(function() {

        $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD mm:ss'
        });

    });
    </script>
{% endblock javascripts %}    

src/AppBundle/Resources/views/admin/jurisdictionCaseNotes.html.twig
{% extends 'AppBundle::adminbase.html.twig' %}
{% block title %}Dashboard - Student Hub Admin{% endblock %}

{% block stylesheets %}          
    {{ parent() }}
    <!-- DataTables CSS -->
    <link href="/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/bootstrap-datetimepicker-master/build/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block pagecontent %}    
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{jurisdiction.name}} <a href="{{path('lexfutures_admin_jurisdiction_cases', {'id': jurisdiction.id})}}"><img src="/images/back-btn.jpg" style="height: 40px;"></a></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                {% for flashMessage in app.session.flashbag.get('successmsg') %}
                    <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scgreen"></i> Success!</strong> {{ flashMessage }}</div>
                {% endfor %}
                {% for flashMessage in app.session.flashbag.get('errormsg') %}
                    <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scred"></i> Error!</strong> {{ flashMessage }}</div>
                {% endfor %}                
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Add a Notes to {{courtcase.name}}                            
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <form action="" method="post" id="stdform" name="updateform">
                                <div class="col-xs-8 col-md-4">
                                    <div class="form-group">
                                        {{ form_row(form.note, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control'} })}}
                                    </div>
                                                                        
                                    <div class="form-group">
                                        <input type="submit" value="Add Note" class="smbt-button btn btn-primary">
                                    </div>
                                    {{ form_rest(form) }}
                                </div> 
                                </form>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Notes for this case                            
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Date added</th> 
                                            <th>Note</th>
                                            <th>Added By</th> 
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for record in courtcase.notes %}
                                        <tr class="odd">
                                            <td>{{ record.created|date('d M Y') }}</td>
                                            <td>{{ record.note }}</td>
                                            <td>
                                                {{ record.creator.fullname }}
                                            </td>   
                                            
                                            <td class="center">                                                
                                                <a href="{{ path('lexfutures_admin_jurisdiction_case_note_edit', {'id': record.id}) }}"><i class="fa fa-pencil action-icon icon-yellow"></i></a>&nbsp;&nbsp; 
                                                <a href="{{ path('lexfutures_admin_jurisdiction_case_note_delete', {'id': record.id}) }}"><i class="fa fa-trash action-icon icon-red"></i></a>&nbsp;&nbsp;
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
        <!-- /#page-wrapper -->
{% endblock pagecontent %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/bootstrap-datetimepicker-master/build/js/bootstrap-datetimepicker.min.js"></script>    
    <script>
    $(document).ready(function() {

        $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD hh:mm'
        });

    });
    </script>
{% endblock javascripts %}    

src/AppBundle/Resources/views/admin/userPredictions.html.twig
{% extends 'AppBundle::adminbase.html.twig' %}
{% block title %}Dashboard - Student Hub Admin{% endblock %}

{% block stylesheets %}          
    {{ parent() }}
    <!-- DataTables CSS -->
    <link href="/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/bootstrap-datetimepicker-master/build/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block pagecontent %}    
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                {% for flashMessage in app.session.flashbag.get('successmsg') %}
                    <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scgreen"></i> Success!</strong> {{ flashMessage }}</div>
                {% endfor %}
                {% for flashMessage in app.session.flashbag.get('errormsg') %}
                    <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scred"></i> Error!</strong> {{ flashMessage }}</div>
                {% endfor %}                
                </div>
            </div>
                        
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Courtcase predictions made by {{user.fullname}}                          
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Date</th> 
                                            <th>Courtcase</th> 
                                            <th>Prediction</th>
                                            <th>Points</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for record in predictions %}
                                        <tr class="odd">
                                            <td>{{ record.created|date('d.M.Y - G:i') }}</td>
                                            <td>{{ record.courtcase.name }}</td>                                            
                                            <td class="center">   
                                                {{ record }}
                                            </td>
                                            <td>
                                                {{record.getScore}} pts
                                            </td>
                                            <td>
                                                <a href="{{ path('lexfutures_admin_jurisdiction_prediction_view', {'id': record.id}) }}"><i class="fa fa-eye action-icon icon-red"></i></a>&nbsp;&nbsp;
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
        <!-- /#page-wrapper -->
{% endblock pagecontent %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/bootstrap-datetimepicker-master/build/js/bootstrap-datetimepicker.min.js"></script>    
    <script>
    $(document).ready(function() {

        $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD hh:mm'
        });

    });
    </script>
{% endblock javascripts %}    