src/AppBundle/Entity/Courtcase.php
<?php

namespace AppBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Courtcase
 *
 * @ORM\Table(name="courtcase")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CourtcaseRepository")
 */
class Courtcase
{
    
    const STATUS_DRAFT = 1;
    const STATUS_PUBLISHED = 2;
    const STATUS_DECIDED = 3;
    const STATUS_DELETED = 4;
    
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var \DateTime $created
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var \DateTime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;
    
    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="is_league", type="boolean", nullable=true)
     */
    private $isLeague;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="is_paused", type="boolean", nullable=true)
     */
    private $isPaused;
    
    /**
     * @var bool
     *
     * @ORM\Column(name="removed_from_role", type="boolean", nullable=true)
     */
    private $removedFromRole;
    
    /**
     * One Courtcase has Many Notes.
     * @ORM\OneToMany(targetEntity="Note", mappedBy="courtcase")
     */
    private $notes;
    
    /**
     * @var \DateTime
     * 
     * @ORM\Column(name="scheduled_date", type="datetime", nullable=true)
     * 
     * @Assert\NotBlank(
     *      message = "Deadline for offers date required"
     * )
     */
    private $scheduledDate;
    
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     * 
     * @Assert\NotBlank(
     *      message = "Name is required"
     * )
     */
    private $name;
    
    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status;
    
    /**
     * 
     * @ORM\ManyToOne(targetEntity="Jurisdiction", inversedBy="courtcases")
     * @ORM\JoinColumn(name="jurisdiction_id", referencedColumnName="id")
     * 
     */
    private $jurisdiction;
    
    /**
     * 
     * @ORM\ManyToOne(targetEntity="Season", inversedBy="courtcases")
     * @ORM\JoinColumn(name="season_id", referencedColumnName="id")
     * 
     */
    private $season;
    
    /**
     * 
     * @ORM\OneToMany(targetEntity="Prediction", mappedBy="courtcase")
     */
    private $predictions;
    
    /**
     * Many Courtcases have Many Judges.
     * @ORM\ManyToMany(targetEntity="Judge", inversedBy="courtcases")
     * @ORM\JoinTable(name="judges_courtcases")
     */
    private $judges;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        
        $this->status = self::STATUS_DRAFT;
        
        $this->judges = new \Doctrine\Common\Collections\ArrayCollection();
        
        $this->notes = new \Doctrine\Common\Collections\ArrayCollection();
        
    }
    
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Courtcase
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return Courtcase
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return Courtcase
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set scheduledDate
     *
     * @param \DateTime $scheduledDate
     *
     * @return Courtcase
     */
    public function setScheduledDate($scheduledDate)
    {
        $this->scheduledDate = $scheduledDate;

        return $this;
    }

    /**
     * Get scheduledDate
     *
     * @return \DateTime
     */
    public function getScheduledDate()
    {
        return $this->scheduledDate;
    }

    /**
     * Set status
     *
     * @param integer $status
     *
     * @return Courtcase
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set jurisdiction
     *
     * @param \AppBundle\Entity\Jurisdiction $jurisdiction
     *
     * @return Courtcase
     */
    public function setJurisdiction(\AppBundle\Entity\Jurisdiction $jurisdiction = null)
    {
        $this->jurisdiction = $jurisdiction;

        return $this;
    }

    /**
     * Get jurisdiction
     *
     * @return \AppBundle\Entity\Jurisdiction
     */
    public function getJurisdiction()
    {
        return $this->jurisdiction;
    }

    /**
     * Add prediction
     *
     * @param \AppBundle\Entity\Prediction $prediction
     *
     * @return Courtcase
     */
    public function addPrediction(\AppBundle\Entity\Prediction $prediction)
    {
        $this->predictions[] = $prediction;

        return $this;
    }

    /**
     * Remove prediction
     *
     * @param \AppBundle\Entity\Prediction $prediction
     */
    public function removePrediction(\AppBundle\Entity\Prediction $prediction)
    {
        $this->predictions->removeElement($prediction);
    }

    /**
     * Get predictions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPredictions()
    {
        return $this->predictions;
    }
    
    
    public function getStatusToString()
    {
        
        if ($this->getStatus() === self::STATUS_DECIDED || $this->getRuling()) {
            
            return "decided";
            
        }
        
        // TODO update this check to ensure that cases become 'upcoming' at midnight of the hearing date
        if ($this->getStatus() === self::STATUS_PUBLISHED) {
            
            if ($this->checkIfClosed()) {
                
                return 'upcoming';
                
            } else {
                
                return 'recently-heard';
                
            }
            
        }
        
        
        
    }
    
    public function checkIfClosed()
    {
        
        /*
        if ($this->getScheduledDate() > new \DateTime()) {
            
            return true;
            
        }
        */
        
        $current = new \DateTime();
        
        if ($this->getScheduledDate()->format("Y-m-d") > $current->format("Y-m-d")) {
            
            return true;
            
        }
        
        return false;
        
    }
    
    /**
     * Add judge
     *
     * @param \AppBundle\Entity\Judge $judge
     *
     * @return Courtcase
     */
    public function addJudge(\AppBundle\Entity\Judge $judge)
    {
        $this->judges[] = $judge;

        return $this;
    }

    /**
     * Remove judge
     *
     * @param \AppBundle\Entity\Judge $judge
     */
    public function removeJudge(\AppBundle\Entity\Judge $judge)
    {
        $this->judges->removeElement($judge);
    }

    /**
     * Get judges
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getJudges()
    {
        return $this->judges;
    }
    
    public function getUserPredictions()
    {
        
        $results = array();
        
        foreach ($this->getPredictions() as $prediction) {
            
            if (!$prediction->getIsRuling()) {
                
                $results[] = $prediction;
                
            }
            
        }
        
        return $results;
        
    }
    
    public function getRuling()
    {
        
        foreach ($this->getPredictions() as $prediction) {
            
            if ($prediction->getIsRuling()) {
                
                return $prediction;
                
            }
            
        }
        
        return null;
        
    }
    
    
    public function getCrowdPrediction()
    {
        
        $crowd = "";
        
        $upheld = $notupheld = $total = 0;
        
        foreach ($this->getPredictions() as $prediction) {
            
            if (!$prediction->getIsRuling()) {
                
                $total += 1;
                
                $predictionScores = $this->scorifyPrediction($prediction);
                
                $upheld = $upheld + $predictionScores["upheld"];
                
                $notupheld = $notupheld + $predictionScores["dismissed"];
                
            }
            
        }
        
        if ($total === 0) {
            
            return "";
            
        } else {
            
            if ($upheld > $notupheld) {
                
                $upheld = ceil($upheld / $total);
                
                $notupheld = floor($notupheld / $total);
                
                return $upheld ." - ".$notupheld . " Appeal will be upheld";

            } else if ($upheld < $notupheld) {

src/AppBundle/Controller/CasesadminController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;

use AppBundle\Service\Util;
use AppBundle\Form\JurisdictionType;
use AppBundle\Form\CourtcaseAdminType;

use AppBundle\Entity\Jurisdiction;
use AppBundle\Entity\File;
use AppBundle\Entity\Courtcase;
use AppBundle\Entity\Judge;
use AppBundle\Entity\User;
use AppBundle\Entity\Note;
use AppBundle\Entity\Prediction;


class CasesadminController extends Controller
{
        
    
    /**
     * @Route("/admin/cases/list", name="lexfutures_admin_cases_list")
     */
    public function casesListAction(Request $request)
    {
        
        $cases = $this->getDoctrine()->getRepository('AppBundle:Courtcase')->findAll();
                
        $util = $this->get(Util::class);
        
        $stats = $util->getDashboardStats($this->getUser());
        
        return $this->render('AppBundle:casesadmin:list.html.twig', [
            'cases' => $cases,
            'stats' => $stats
        ]);
        
    }
    
    /**
     * @Route("/admin/cases/add", name="lexfutures_admin_case_add")
     */
    public function casesAddAction(Request $request)
    {
        
        //$jurisdictions = $this->getDoctrine()->getRepository('AppBundle:Courtcase')->findAll();
        $em = $this->getDoctrine()->getManager();
        
        $util = $this->get(Util::class);
        
        $stats = $util->getDashboardStats($this->getUser());
        
        $courtcase = new Courtcase();
        
        $courtcase->setStatus(Courtcase::STATUS_PUBLISHED);
        
        $form = $this->createForm('AppBundle\Form\CourtcaseAdminType', $courtcase,[]);
        
        if ($request->getMethod() == 'POST') {
            
            $form->handleRequest($request);
            
            $jurisdiction = $courtcase->getJurisdiction();
            
            //$courtcase->setScheduledDate(new \DateTime($courtcase->getScheduledDate()));
            
            if ($form->isValid()) {
                
                foreach ($jurisdiction->getActiveJudges() as $judge) {
                    
                    if ($judge->getJusticeTitle()->getId() < 4) {
                        
                        $courtcase->addJudge($judge);
                        
                    }
                }
                
                $em->persist($courtcase);
            
                $em->flush();
                
                $this->get('session')->getFlashBag()->add("successmsg", $courtcase->getName(). " has been added!");
            
                return $this->redirectToRoute('lexfutures_admin_case_add', []);
                
            } else {
                
                $this->get('session')->getFlashBag()->add("errormsg", "Could not load Court Case!");
            
                return $this->redirectToRoute('lexfutures_admin_case_add', []);
                
            }
                        
        }
        
        return $this->render('AppBundle:casesadmin:add.html.twig', [
            'stats' => $stats,
            'form' => $form->createView()
        ]);
        
    }
    
    
}

src/AppBundle/Resources/views/casesadmin/add.html.twig
{% extends 'AppBundle::adminbase.html.twig' %}
{% block title %}Dashboard - Student Hub Admin{% endblock %}

{% block stylesheets %}          
    {{ parent() }}
    <!-- DataTables CSS -->
    <link href="/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/bootstrap-datetimepicker-master/build/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block pagecontent %}    
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Add Courtcase</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                {% for flashMessage in app.session.flashbag.get('successmsg') %}
                    <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scgreen"></i> Success!</strong> {{ flashMessage }}</div>
                {% endfor %}
                {% for flashMessage in app.session.flashbag.get('errormsg') %}
                    <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scred"></i> Error!</strong> {{ flashMessage }}</div>
                {% endfor %}                
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Add a Court Case                          
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <form action="" method="post" id="stdform" name="updateform">
                                <div class="col-xs-8 col-md-4">
                                    <div class="form-group">
                                        {{ form_row(form.jurisdiction, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control'} })}}
                                    </div>
                                    <div class="form-group">
                                        {{ form_row(form.name, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control'} })}}
                                    </div>
                                    <div class="form-group">
                                        {{ form_row(form.scheduledDate, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control datetimepicker'} })}}
                                    </div>
                                    <div class="form-group">
                                        {{ form_row(form.isLeague, {'label_attr': {'class': 'label label-default'}, 'attr': {'class': 'form-control'} })}}
                                    </div>
                                    
                                    <div class="form-group">
                                        <input type="submit" value="Add Court Case" class="smbt-button btn btn-primary">
                                    </div>
                                    {{ form_rest(form) }}
                                </div> 
                                </form>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
{% endblock pagecontent %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="/js/moment.js"></script>
    <script type="text/javascript" src="/bootstrap-datetimepicker-master/build/js/bootstrap-datetimepicker.min.js"></script>    
    <script>
    $(document).ready(function() {

        $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD hh:mm'
        });

    });
    </script>
{% endblock javascripts %}    

src/AppBundle/Resources/views/casesadmin/list.html.twig
{% extends 'AppBundle::adminbase.html.twig' %}
{% block title %}Dashboard - Cases{% endblock %}

{% block stylesheets %}          
    {{ parent() }}
    <!-- DataTables CSS -->
    <link href="/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
{% endblock %}

{% block pagecontent %}    
    <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">All cases</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                {% for flashMessage in app.session.flashbag.get('successmsg') %}
                    <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scgreen"></i> Success!</strong> {{ flashMessage }}</div>
                {% endfor %}
                {% for flashMessage in app.session.flashbag.get('errormsg') %}
                    <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><strong><i class="fa fa-check scred"></i> Error!</strong> {{ flashMessage }}</div>
                {% endfor %}                
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Table of Court Cases for all Jurisdictions
                            <span style="float: right;"><a href="{{ path('lexfutures_admin_case_add')}}"><i class="fa fa-bank"></i> Add a new Court Case</a></span>
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Date added</th> 
                                            <th>Name</th>
                                            <th>Jurisdiction</th>
                                            <th>Status</th> 
                                            <th>Hearing Date</th>
                                            <th>Outcome</th>
                                            <th>Predictions</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for record in cases %}
                                        <tr class="odd">
                                            <td>{{ record.created|date('d M Y') }}</td>
                                            <td>{{ record.name }}</td>
                                            <td>{{ record.jurisdiction.name }}</td>
                                            <td>
                                                {{ record.publicationStatusToString }}
                                            </td>   
                                            <td>{{ record.scheduledDate|date('d M Y') }}</td>
                                            <td>
                                                {% if record.ruling is defined and record.ruling is not null %}
                                                {{record.ruling}}
                                                {% endif %}
                                            </td>
                                            <td class="text-center">
                                                <a href="{{ path('lexfutures_admin_jurisdiction_case_predictions', {'slug': record.slug}) }}">{{record.userPredictions|length}}</a>
                                            </td>
                                            <td class="center" width="220"> 
                                                {% if record.publicationStatusToString != "deleted" %}
                                                <a title="Edit This Case" href="{{ path('lexfutures_admin_jurisdiction_case_edit', {'id': record.jurisdiction.id, 'caseid': record.id}) }}"><i class="fa fa-pencil action-icon icon-yellow"></i></a>&nbsp;&nbsp;
                                                {% if record.isPaused is not null and record.isPaused %}
                                                <a title="Pause User Predictions For This Case" href="{{ path('lexfutures_admin_jurisdiction_case_pause_toggle', {'id': record.jurisdiction.id, 'caseid': record.id, 'action': 'unpause'}) }}"><i class="fa fa-play action-icon icon-orange"></i></a>&nbsp;&nbsp;
                                                {% else %}
                                                <a title="Pause User Predictions For This Case" href="{{ path('lexfutures_admin_jurisdiction_case_pause_toggle', {'id': record.jurisdiction.id, 'caseid': record.id, 'action': 'pause'}) }}"><i class="fa fa-pause action-icon icon-orange"></i></a>&nbsp;&nbsp;
                                                {% endif %}
                                                <a title="List Judges" href="{{ path('lexfutures_admin_jurisdiction_case_judges', {'slug': record.slug}) }}"><i class="fa fa-user action-icon icon-green"></i></a>&nbsp;&nbsp;
                                                {% if record.ruling is defined and record.ruling is not null %}
                                                <a title="Ruling Summary For This Case" href="{{ path('lexfutures_admin_jurisdiction_case_ruling_summary', {'id': record.id}) }}"><i class="fa fa-list action-icon icon-blue"></i></a>&nbsp;&nbsp;
                                                {% else %}
                                                <a title="Ruling For This Case" href="{{ path('lexfutures_admin_jurisdiction_case_ruling', {'id': record.id}) }}"><i class="fa fa-gavel action-icon icon-blue"></i></a>&nbsp;&nbsp;
                                                {% endif %}
                                                <a title="Notes For This Case" href="{{ path('lexfutures_admin_jurisdiction_case_notes', {'slug': record.slug}) }}"><i class="fa fa-file-text-o action-icon icon-green"></i></a>&nbsp;&nbsp;
                                                <a title="Delete This Case" href="{{ path('lexfutures_admin_jurisdiction_case_delete', {'slug': record.slug}) }}"><i class="fa fa-trash action-icon icon-red" aria-hidden="true"></i></a>&nbsp;&nbsp;
                                                {% endif %}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
{% endblock pagecontent %}
{% block javascripts %}
    {{ parent() }}
    
    <!-- DataTables JavaScript -->
    <script src="/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script src="/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
    
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true,
            pageLength: 50
        });
    });
    </script>
{% endblock javascripts %}    